### ISSUE TITLE
Implement PMT function as SDF

### ISSUE THREAD

**Issue by fbie** [popular-parallel-programming/funcalc-euses#7]
See https://support.office.com/en-us/article/PMT-function-0214DA64-9A63-4996-BC20-214433FA6441

- [x] `financial\processed\financial-model-spreadsheet.xml`

**Comment by hborum** [comment]
Do you have any reference for an implementation? 
I tried to implement RATE() from https://www.excelforum.com/excel-general/559235-interest-rate-mathematical-formula.html however it turned out to give a different result than excel. Also the algorithm from the link ignores some of the arguments. So far I have kept it since it least gives a function that requires some computations.

**Comment by fbie** [comment]
In Spreadsheet Implementation Technology, there is a reference to Jens Zeilund Sørensen's master's thesis from 2012, which you can access [here](http://itu.dk/people/fbie/soerensen-msc-thesis.pdf). It seems to provide sheet-defined functions for both, `RATE` and `PMT`.  The former, however, seems to rely on `GOALSEEK`, which is part of testsdf.xml.

Let me know if this turns out to be too troublesome and we'll look at what we can do about it.

**Comment by hborum** [comment]
Ok, I will try to look at these two

**Comment by hborum** [comment]
I have looked a bit at it and have a new RATE implementation that is still gives very different results than Excel. However I have omitted this check since I don't understand it:
`= if(_raisable(B92,B93),D93,ERR("r is not raisable to nper")`
Do you have any idea what _raisable means, I would guess that it means that i can't find a power that raises r to nper, in other words that no x satisfies: `r^x = nper`

Is it important to you that Rate returns the correct value? It is likely I have some done something wrong when rewriting the function.

Also the thesis does not seem to have an implementation of PMT in the written part, do you have the implementation code. The corresponding function in F# is probably enough.

**Comment by fbie** [comment]
> Is it important to you that Rate returns the correct value? It is likely I have some done something wrong when rewriting the function.

Correct would be better; let's discuss that at the next meeting.

> Also the thesis does not seem to have an implementation of PMT in the written part, do you have the implementation code. The corresponding function in F# is probably enough.

Unfortunately, I don't. Maybe Peter @sestoft can help here?

**Comment by sestoft** [comment]
On 2Aug17, 18:40, "Florian Biermann" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it important to you that Rate returns the correct value? It is likely I have some done something wrong when rewriting the function.

Correct would be better; let's discuss that at the next meeting.

Jens Zeilund tested his implementations against F# test code that had been tested against Excel, so should be correct (though in some cases it is impossible to get the exact same bits as Excel).

Also the thesis does not seem to have an implementation of PMT in the written part, do you have the implementation code. The corresponding function in F# is probably enough.

Unfortunately, I don't. Maybe Peter @sestoft<https://github.com/sestoft> can help here?

With a delay of only 5 years I've put the thesis and code at http://www.itu.dk/people/sestoft/funcalc/

Peter

**Comment by sestoft** [comment]
On 2Aug17, 16:33, "Holger Borum" <notifications@github.com<mailto:notifications@github.com>> wrote:

I have looked a bit at it and have a new RATE implementation that is still gives very different results than Excel. However I have omitted this check since I don't understand it:
= if(_raisable(B92,B93),D93,ERR("r is not raisable to nper")
Do you have any idea what _raisable means, I would guess that it means that i can't find a power that raises r to nper, in other words that no x satisfies: r^x = nper

That sounds plausible...

Also the thesis does not seem to have an implementation of PMT in the written part, do you have the implementation code. The corresponding function in F# is probably enough.

Jens Zeilund did implement PMT, according to Figure 6.2 in the Spreadsheet Implementation book.

The F# implementation of Excel functions can be found at http://fsprojects.github.io/ExcelFinancialFunctions/ -- apparently Microsoft cannot even maintain a website called http://archive.msdn.microsoft.com/

Peter

**Comment by fbie** [comment]
> With a delay of only 5 years I've put the thesis and code at http://www.itu.dk/people/sestoft/funcalc/ 

I've also added it to [funcalc-examples](https://github.com/popular-parallel-programming/funcalc-examples).
